{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "harbor-labeler.fullname" . }}
  labels:
    app: {{ template "harbor-labeler.name" . }}
    {{- include "harbor-labeler.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    # paged discovery only reads pods cluster-wide
    verbs: ["list"]
{{- end }}
